all: stack

stack:
	gcc -g -Wall -std=gnu11 -m32 -w stack.c -o stack

bitops:
	gcc -g -Wall -std=gnu11 -m32 -w bitops.c -o bitops

threads:
	gcc -g -Wall -std=gnu11 -m32 -w threads.c -o threads

clean:
	rm -rf stack bitops threads